In [5]:
import numpy as np
A = np.array([[25,0,1],[20,1,2],[40,1,6]])
b = np.array([[110],[110],[210]])

# To see rank, use: 
# np.linalg.matrix_rank(A)

# To invert a matrix, use:
# np.linalg.inv(A)

# To multiply matrices in Python 3, use:
# A@B

In [6]:
np.linalg.solve(A,b)

array([[ 4.25],
       [17.5 ],
       [ 3.75]])

In [30]:
import numpy as np
A = np.array([[25,15,10,0,1],[20,12,8,1,2],[40,30,10,1,6], [30,15,15,0,3], [35,20,15,2,4]])
b = np.array([[104],[97],[193],[132],[174]])

print(np.linalg.matrix_rank(A))
#print(np.linalg.matrix_rank(A[:,1:]))

# Note: you can use np.hstack() to concatinate vectors, for example np.hstack((A,b))
print(np.linalg.matrix_rank(np.hstack((A,b))))

# Note: you can select all the columns, except the first of a matrix A as:  A[:,1:]
#print(np.linalg.solve(A[:,1:], b))
A = A[:,1:]
print(np.linalg.inv(A.T@A)@A.T@b)

4
4
[[4.]
 [4.]
 [9.]
 [4.]]


In [15]:
A[:,1:]

array([[15, 10,  0,  1],
       [12,  8,  1,  2],
       [30, 10,  1,  6],
       [15, 15,  0,  3],
       [20, 15,  2,  4]])

In [12]:
np.hstack((A,b))

array([[ 25,  15,  10,   0,   1, 104],
       [ 20,  12,   8,   1,   2,  97],
       [ 40,  30,  10,   1,   6, 193],
       [ 30,  15,  15,   0,   3, 132],
       [ 35,  20,  15,   2,   4, 174]])

In [18]:
b[1:]

array([[ 97],
       [193],
       [132],
       [174]])

In [24]:
A = np.array([[1, -0.5, 1],[0, 1.5, 0],[0, 1.5, 0], [1, -0.5, 1]])
print(np.linalg.matrix_rank(A))

2


In [26]:
np.matrix.transpose(A)

array([[ 1. ,  0. ,  0. ,  1. ],
       [-0.5,  1.5,  1.5, -0.5],
       [ 1. ,  0. ,  0. ,  1. ]])

In [25]:
np.matmul(np.matrix.transpose(A), A)

array([[ 2., -1.,  2.],
       [-1.,  5., -1.],
       [ 2., -1.,  2.]])