In [10]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt 
import math

def gram_schmidt(B):
    """Orthogonalize a set of vectors stored as the columns of matrix B."""
    # Get the number of vectors.
    m, n = B.shape
    # Create new matrix to hold the orthonormal basis
    U = np.zeros([m,n]) 
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        v = B[:,j].copy()
        for k in range(j):
            v -= np.dot(U[:, k], B[:, j]) * U[:, k]
        if np.linalg.norm(v)>1e-10:
            U[:, j] = v / np.linalg.norm(v)
    return U

if __name__ == '__main__':
    B1 = np.array([[1.0, 1.0, 0.0], [2.0, 2.0, 0.0], [2.0, 2.0, 1.0]])
    A1 = gram_schmidt(B1)
    print(A1)
    A2 = gram_schmidt(np.random.rand(4,2)@np.random.rand(2,5))
    print(A2.transpose()@A2)

[[ 0.33333333  0.         -0.2981424 ]
 [ 0.66666667  0.         -0.59628479]
 [ 0.66666667  0.          0.74535599]]
[[ 1.00000000e+00 -9.54791801e-15  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-9.54791801e-15  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]]


In [18]:
in_data = loadmat('movie.mat')
X = in_data['X']
X[:5,]

array([[ 4,  7,  2,  8,  7,  4,  2],
       [ 9,  3,  5,  6, 10,  5,  5],
       [ 4,  8,  3,  7,  6,  4,  1],
       [ 9,  2,  6,  5,  9,  5,  4],
       [ 4,  9,  2,  8,  7,  4,  1]], dtype=uint8)

(a) Is the first basis vector you obtain equal to t1?

In [6]:
X_a = np.hstack((np.ones((len(X), 1)), X))
X_a[:5,]

array([[ 1.,  4.,  7.,  2.,  8.,  7.,  4.,  2.],
       [ 1.,  9.,  3.,  5.,  6., 10.,  5.,  5.],
       [ 1.,  4.,  8.,  3.,  7.,  6.,  4.,  1.],
       [ 1.,  9.,  2.,  6.,  5.,  9.,  5.,  4.],
       [ 1.,  4.,  9.,  2.,  8.,  7.,  4.,  1.]])

In [17]:
gs = gram_schmidt(X_a)
gs[:,0] ==  1 / math.sqrt(5)

array([ True,  True,  True,  True,  True])

Yes, they are same.

(b) Find W so that X ~ t1W. Also compute the residual eror X - t1W

In [20]:
t1 = gs[:,0].reshape(5,1)
t1

array([[0.4472136],
       [0.4472136],
       [0.4472136],
       [0.4472136],
       [0.4472136]])

In [21]:
w = np.transpose(t1) @ X
w

array([[13.41640786, 12.96919427,  8.04984472, 15.20526225, 17.44133022,
         9.8386991 ,  5.81377674]])

In [22]:
baseline_rating = t1 @ w
baseline_rating

array([[6. , 5.8, 3.6, 6.8, 7.8, 4.4, 2.6],
       [6. , 5.8, 3.6, 6.8, 7.8, 4.4, 2.6],
       [6. , 5.8, 3.6, 6.8, 7.8, 4.4, 2.6],
       [6. , 5.8, 3.6, 6.8, 7.8, 4.4, 2.6],
       [6. , 5.8, 3.6, 6.8, 7.8, 4.4, 2.6]])

In [23]:
residual = X - baseline_rating
residual

array([[-2. ,  1.2, -1.6,  1.2, -0.8, -0.4, -0.6],
       [ 3. , -2.8,  1.4, -0.8,  2.2,  0.6,  2.4],
       [-2. ,  2.2, -0.6,  0.2, -1.8, -0.4, -1.6],
       [ 3. , -3.8,  2.4, -1.8,  1.2,  0.6,  1.4],
       [-2. ,  3.2, -1.6,  1.2, -0.8, -0.4, -1.6]])

(c) Find a rank-2 approximation using T = [t1 t2]. Compute residual error X - TW.

In [25]:
t2 = gs[:,1].reshape(5,1)
t2

array([[-0.36514837],
       [ 0.54772256],
       [-0.36514837],
       [ 0.54772256],
       [-0.36514837]])

In [26]:
T = np.hstack((t1, t2))
T

array([[ 0.4472136 , -0.36514837],
       [ 0.4472136 ,  0.54772256],
       [ 0.4472136 , -0.36514837],
       [ 0.4472136 ,  0.54772256],
       [ 0.4472136 , -0.36514837]])

In [28]:
w2 = np.transpose(T) @ X
w2

array([[13.41640786, 12.96919427,  8.04984472, 15.20526225, 17.44133022,
         9.8386991 ,  5.81377674],
       [ 5.47722558, -6.02494813,  3.46890953, -2.37346442,  3.10376116,
         1.09544512,  3.46890953]])

In [29]:
TW = T @ w2

In [30]:
residual = X - TW
residual

array([[ 1.77635684e-15, -1.00000000e+00, -3.33333333e-01,
         3.33333333e-01,  3.33333333e-01,  1.77635684e-15,
         6.66666667e-01],
       [-3.55271368e-15,  5.00000000e-01, -5.00000000e-01,
         5.00000000e-01,  5.00000000e-01, -1.77635684e-15,
         5.00000000e-01],
       [ 1.77635684e-15,  2.66453526e-15,  6.66666667e-01,
        -6.66666667e-01, -6.66666667e-01,  1.77635684e-15,
        -3.33333333e-01],
       [-3.55271368e-15, -5.00000000e-01,  5.00000000e-01,
        -5.00000000e-01, -5.00000000e-01, -1.77635684e-15,
        -5.00000000e-01],
       [ 1.77635684e-15,  1.00000000e+00, -3.33333333e-01,
         3.33333333e-01,  3.33333333e-01,  1.77635684e-15,
        -3.33333333e-01]])

No stark difference between sci-fi and romance.

(d) Rank-3 approxiamtion using T = [t1 t2 t3]. Compute reisudal error.

In [32]:
t3 = gs[:,2].reshape(5,1)
t3

array([[-6.32455532e-01],
       [ 3.16227766e-01],
       [ 1.96606674e-15],
       [-3.16227766e-01],
       [ 6.32455532e-01]])

In [33]:
T3 = np.hstack((t1, t2, t3))
T3

array([[ 4.47213595e-01, -3.65148372e-01, -6.32455532e-01],
       [ 4.47213595e-01,  5.47722558e-01,  3.16227766e-01],
       [ 4.47213595e-01, -3.65148372e-01,  1.96606674e-15],
       [ 4.47213595e-01,  5.47722558e-01, -3.16227766e-01],
       [ 4.47213595e-01, -3.65148372e-01,  6.32455532e-01]])

In [35]:
w3 = np.transpose(T3) @ X
w3

array([[ 1.34164079e+01,  1.29691943e+01,  8.04984472e+00,
         1.52052622e+01,  1.74413302e+01,  9.83869910e+00,
         5.81377674e+00],
       [ 5.47722558e+00, -6.02494813e+00,  3.46890953e+00,
        -2.37346442e+00,  3.10376116e+00,  1.09544512e+00,
         3.46890953e+00],
       [ 7.99360578e-15,  1.58113883e+00, -3.16227766e-01,
         3.16227766e-01,  3.16227766e-01,  1.50990331e-14,
        -3.16227766e-01]])

In [36]:
TW3 = T3 @ w3
TW3

array([[4.        , 7.        , 2.53333333, 7.46666667, 6.46666667,
        4.        , 1.53333333],
       [9.        , 3.        , 5.4       , 5.6       , 9.6       ,
        5.        , 4.4       ],
       [4.        , 8.        , 2.33333333, 7.66666667, 6.66666667,
        4.        , 1.33333333],
       [9.        , 2.        , 5.6       , 5.4       , 9.4       ,
        5.        , 4.6       ],
       [4.        , 9.        , 2.13333333, 7.86666667, 6.86666667,
        4.        , 1.13333333]])

In [37]:
residual = X - TW3
residual

array([[ 6.66133815e-15,  2.75335310e-14, -5.33333333e-01,
         5.33333333e-01,  5.33333333e-01,  1.15463195e-14,
         4.66666667e-01],
       [-5.32907052e-15, -1.37667655e-14, -4.00000000e-01,
         4.00000000e-01,  4.00000000e-01, -6.21724894e-15,
         6.00000000e-01],
       [ 1.77635684e-15,  0.00000000e+00,  6.66666667e-01,
        -6.66666667e-01, -6.66666667e-01,  1.77635684e-15,
        -3.33333333e-01],
       [-1.77635684e-15,  1.31006317e-14,  4.00000000e-01,
        -4.00000000e-01, -4.00000000e-01,  2.66453526e-15,
        -6.00000000e-01],
       [-3.55271368e-15, -2.66453526e-14, -1.33333333e-01,
         1.33333333e-01,  1.33333333e-01, -7.99360578e-15,
        -1.33333333e-01]])